/*
 * This file is part of dui.
 * 
 * dui is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or
 * (at your option) any later version.
 * 
 * dui is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with dui; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/*
 * - automatically generated by gtk2dui (dAntE)
 * - pos-processed by Antonio Monteiro
 */

module dui.SeparatorToolItem;

private import def.Types;
private import def.Constants;

private import dui.ToolItem;

private struct GtkSeparatorToolItem;


private:
extern(C)
{
	GtkToolItem* gtk_separator_tool_item_new    ();
	void        gtk_separator_tool_item_set_draw(GtkSeparatorToolItem *item,gboolean draw);
	gboolean    gtk_separator_tool_item_get_draw(GtkSeparatorToolItem *item);
}

/**
 * A GtkSeparatorItem is a GtkToolItem that separates groups of other GtkToolItems.
 * Depending on the theme, a GtkSeparatorToolItem will often look like a vertical
 * line on horizontally docked toolbars. If the property "expand" is TRUE and the
 * property "draw" is FALSE, a GtkSeparatorToolItem will act as a "spring" that
 * forces other items to the ends of the toolbar. Use
 * gtk_separator_tool_item_new() to create a new GtkSeparatorToolItem.
 */
public
class SeparatorToolItem : ToolItem
{

	protected:

	GtkSeparatorToolItem* gtkSeparatorToolItem;

	public:

	/**
	 * Creates a SeparatorToolItem from a GtkSeparatorToolItem
	 * @param *gtkWidget the gtk struct address pointer
	 * @return 
	 */
    this(GtkToolItem* gtkToolItem)
    {
        super(cast(GtkToolItem*)gtkToolItem);
		this.gtkSeparatorToolItem = gtkSeparatorToolItem;
    }


	/**
	 * Create a new GtkSeparatorToolItem
	 * @return the new GtkSeparatorToolItem
	 */
	this()
	{
		this(gtk_separator_tool_item_new());
	}

	/**
	 * When separator_tool_items is drawn as a vertical line, or just blank. Setting this FALSE along with
	 * gtk_tool_item_set_expand() is useful to create an item that forces following items to the end of the
	 * toolbar.
	 * @param item\ufffd a GtkSeparatorToolItem
	 * @param draw\ufffd whether separator_tool_item is drawn as a vertical iln
	 */
	void setDraw(bit draw)
	{
		gtk_separator_tool_item_set_draw(gtkSeparatorToolItem, draw);
	}


	/**
	 * Returns whether separator_tool_item is drawn as a line, or just blank. See gtk_separator_tool_item_set_draw().
	 * @param item\ufffd a GtkSeparatorToolItem
	 * @return TRUE if separator_tool_item is drawn as a line, or just blank.
	 */
	bit getDraw()
	{
		return gtk_separator_tool_item_get_draw(gtkSeparatorToolItem) == 0 ? false : true;
	}


}


/+
gtk_separator_tool_item_new ()

GtkToolItem* gtk_separator_tool_item_new    (void);

Create a new GtkSeparatorToolItem

Returns\ufffd:	the new GtkSeparatorToolItem

Since 2.4
gtk_separator_tool_item_set_draw ()

void        gtk_separator_tool_item_set_draw
                                            (GtkSeparatorToolItem *item,
                                             gboolean draw);

When separator_tool_items is drawn as a vertical line, or just blank. Setting this FALSE along with gtk_tool_item_set_expand() is useful to create an item that forces following items to the end of the toolbar.

item\ufffd:	a GtkSeparatorToolItem
draw\ufffd:	whether separator_tool_item is drawn as a vertical iln

Since 2.4
gtk_separator_tool_item_get_draw ()

gboolean    gtk_separator_tool_item_get_draw
                                            (GtkSeparatorToolItem *item);

Returns whether separator_tool_item is drawn as a line, or just blank. See gtk_separator_tool_item_set_draw().

item\ufffd:	a GtkSeparatorToolItem
Returns\ufffd:	TRUE if separator_tool_item is drawn as a line, or just blank.

Since 2.4 
+/

