#!/usr/bin/bash

set distNumber="00.23_25"

echo make distribution dir
mkdir -p public/dui

echo copy files
cp \
	INSTALL \
	Makefile.DUI \
	README \
	doDist \
	lgpl.txt \
	public/dui
	
echo copy dirs
cp -R \
	doc \
	images \
	screenShots \
	src \
	public/dui
	
cd public

echo remove .svn 

rm -fr dui/.svn
rm -fr dui/*/.svn
rm -fr dui/*/*/.svn
rm -fr dui/*/*/*/.svn
rm -fr dui/*/*/*/*/.svn

echo build tar ball
tar -cf dui.tar dui

echo gzip tar ball
gzip dui.tar

cd ..

mv public/dui.tar.gz .